### ISSUE TITLE
Release 2.0 version to crates.io

### ISSUE THREAD

**Issue by ErwanDL** [routerify/routerify-query#8]
Hello @rousan, I see that this crate has been updated to version 2.0 (to work with routerify v2), but it seems like that version has not been published to crates.io yet. Would it be possible to publish that update, so that we don't have to rely on a git ref to use version 2 of routerify-query ? Thank you.

**Comment by rousan** [comment]
@seanpianka, @gsserge, can you please release a new version `v2.0.0`? Thanks.

**Comment by gsserge** [comment]
Sure! Will do today.

**Comment by gsserge** [comment]
Done!
